[default]
DEBUG = false

[development]
TEMPLATES_AUTO_RELOAD = true
DEBUG = true

EXTENSIONS = [
    "webapp.ext.database",
    "webapp.ext.appearance",
    "webapp.blueprints.navigation",
    "webapp.blueprints.frontend"
]

TITLE = "Smart AniMon"

# host:port -> servidor e porta do MongoDB Server
MONGO_URI="mongodb://user_application:pass_application@host:port/animon_db"