[default]
DEBUG = false

[development]
TEMPLATES_AUTO_RELOAD = true
DEBUG = true

EXTENSIONS = [
    "webapp.ext.database",
    "webapp.ext.appearance",
    "webapp.blueprints.navigation",
    "webapp.blueprints.frontend"
]

TITLE = "Smart AniMon"

# Host -> nome do contêiner do mongo
MONGO_URI="mongodb://user_application:pass_application@mongo/animon_db"